apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: naveen-crole
rules:
  - apiGroups: ["", "autoscaling"]
    resources: ["pods", "services", "horizontalpodautoscalers"]
    verbs: ["create", "list", "get", "watch"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "list", "get"]
