apiVersion: v1
kind: Pod
metadata:
  name: pod-5
  labels:
    app: db
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: instance
                operator: In
                values:
                  - logs
  containers:
    - name: cont-1
      image: nginx
      ports:
        - containerPort: 80
