apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    layer: db
spec:
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "db"
      effect: "NoSchedule"
  containers:
    - name: cont-1
      image: nginx
      ports:
        - containerPort: 80
