apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
    - name: cont-1
      image: nginx
      ports:
        - containerPort: 80

      envFrom:
        - secretRef:
            name: firstsecret

      env:
        - name: db_userpassword
          valueFrom:
            secretKeyRef:
              name: secondsecret
              key: db_pass
