apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: swiggy
    env: dev
    client: tcs
spec:
  nodeSelector:
    worker: worker1
  containers:
    - name: cont-1
      image: nginx
      ports:
        - containerPort: 80
